name: ML
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - scipy==1.10.1
    - seaborn==0.12.2
    - plotly==5.13.1
    - pandas==1.5.3
    - ipykernel==6.21.3
    - scikit-learn==1.2.1